import {MessageProducer} from "../message/MessageProducer.ts";
import {MessageHandler} from "../message/MessageHandler.ts";
import {SymTab} from "../intermediate/SymTab.ts";
import {ICode} from "../intermediate/ICode.ts";
import { Message } from "../message/Message.ts";
import { MessageListener } from "../message/MessageListener.ts";


/**
 * <h2>Backend</h2>
 * <p>The framework class that represents the back end component</p>
 */
export abstract class Backend implements MessageProducer {


    protected static messageHandler: MessageHandler;    // Message handler delegate.

    static {
        Backend.messageHandler = new MessageHandler();
    }

    protected symTab: SymTab = {} as SymTab;          // Symbol table.
    protected iCode: ICode = {} as ICode;            // intermediate code.

    /**
     * Process the intermediate code and the symbol table generated by the
     * parser. To be implemented by a compiler or an interpreter subclass.
     * @param iCode the intermediate code.
     * @param symTab the symbol table.
     * @throws {Error} if an error occurred.
     */
    public abstract process(iCode: ICode, symTab: SymTab): void;

    /**
     * @getter
     * @return the Intermediate code.
     */
    public getICode(): ICode {
        return this.iCode;
    }

    /**
     * @getter
     * @return the symbol table.
     */
    public getSymTab(): SymTab {
        return this.symTab;
    }

    /**
     * @getter
     * @return the Message handler.
     */
    public getMessageHandler(): MessageHandler {
        return Backend.messageHandler;
    }

    /**
     * Add a Backend message listener.
     * @param listener the listener to add.
     */
    addMessageListener(listener: MessageListener): void {
        Backend.messageHandler.addListener(listener);
    }

    /**
     * Remove a Backend message listener.
     * @param listener the listener to remove.
     */
    removeMessageListener(listener: MessageListener): void {
        Backend.messageHandler.removeListener(listener);
    }

    /**
     * Notify all Backend Message listeners after setting the message.
     * @param message
     */
    sendMessage(message: Message): void {
        Backend.messageHandler.sendMessage(message);
    }
}